spring:
  application:
    name: fin-twitter
server:
  port: 8084
eureka:
  client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.web: DEBUG
    com.finch: DEBUG