spring:
  application:
    name: fin-processor
server:
  port: 8085
eureka:
  client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.web: DEBUG
    com.finch: DEBUG

feign:
  hystrix:
    enabled: true